version: '3'
services:
  bot:
    build: .
    restart: always
    env_file: .env
    links:
      - 'api'
  api:
    image: puzanov/cryptoexchange_api
    restart: always
    ports:
      - '4567:4567'